version: '3.8'

services:
  camera:
    image: ghcr.io/CyanAutomation/MotionInOcean:latest
    volumes:
      - /run/udev:/run/udev:ro
    ports:
      - "8000:8000"
    restart: always
    privileged: true
